"""updated refresh_tokens table fields

Revision ID: 7302036ec3e7
Revises: 83803acbc409
Create Date: 2026-09-07 06:23:11.570442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7302036ec3e7'
down_revision: Union[str, Sequence[str], None] = '83803acbc409'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('expired_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_column('refresh_tokens', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_column('refresh_tokens', 'expired_at')
    # ### end Alembic commands ###
